dist: trusty

language: node_js

node_js:
  - "10.15.0"

env:
  - provider=http://localhost:8545

before_install:

install:
  - npm ci
  - nohup npm run ganache &

script:
  - npm run lint
  - npm run test
